name: PCST Pipeline on Github
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build Works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.13.0
      - name: Build with mvn
        run: mvn clean install
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.13.0
      - name: Run Junit tests (including integration tests and jacoco coverage)
        run: mvn test
      - name: Create Mutation coverage
        run: "mvn test compile org.pitest:pitest-maven:mutationCoverage"
